baseURL = 'http://confidentialcontainers.org/'
languageCode = 'en-us'
title = 'Confidential Containers'
theme = "docsy"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[params]
# copyright = "The Docsy Authors"
# privacy_policy = "https://policies.google.com/privacy"

version_menu = "Releases"

version = "0.7.0"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/confidential-containers/confidentialcontainers.org"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/confidential-containers"

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false

[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/confidential-containers/confidential-containers/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/confidential-containers/confidential-containers/issues/new">tell us how we can improve</a>.'

[params.links]
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/confidential-containers"
icon = "fab fa-github"
desc = "Development takes place here!"
[[params.links.developer]]
name = "Slack"
url = "https://communityinviter.com/apps/cloud-native/cncf"
icon = "fab fa-slack"
desc = "Chat with other project developers"
# hugo module configuration
